### ISSUE TITLE
MG- secrets vs services 

### ISSUE THREAD

**Issue by LeilaMousapour** [JohnErnsthausen/roc#28]
Hi John @JohnErnsthausen ,

Based on the way you have worded your MG document, I think the order of your thought process was that you first broke down your software into modules and then you tried you find the “secret” or the “anticipated change” based on the design you had come up with. And that is why you have worded the secretes very similar to the service of the module. However, secrets should be more related to the anticipated changes.

**Comment by JohnErnsthausen** [comment]
Hello @LeilaMousapour and Prof @smiths, 

The breakdown into modules is based on the natural breakdown in the theory of radius of convergence.

The power series we consider are (truncated) real power series. What can reduce the radius of convergence from the entire complex plane to some finite circle of convergence? Idea: A singularity.

For real power series, power series where the coefficients and expansion point is real, theory says there can only be poles, logarithmic branch points, and essential singularities on the real axis or in conjugate pairs.

Naturally there should be modules for one real pole and a pair of complex conjugate poles in the case of primary singularities. When there are secondary singularities, there should be a catch all and more heuristic way to resolve the singularity.

Barring some other (yet unknown) knowledge about this problem, it is natural to have these as the modules. Then the secret should be as in the documentation for the solution of ODEs or Linear Equations examples in our Class Notes. What solver to associate with a particular module. This is how I decided the secrets, because the solution methods are likely to change. The solution methods are the anticipated changes plus some bookkeeping modules.
