### ISSUE TITLE
feedback regarding your SRS document

### ISSUE THREAD

**Issue by salahhessien** [JohnErnsthausen/roc#4]
Hello John,

I've reviewed your SRS document, and I see that you have done a pretty good job in terms of the document organization, but unfortunately, I am not a domain expert in your work. Therefore I won't raise many technical concerns here. I will leave this part to the domain expert reviewer to address them, if any.

Thanks,
Salah

**Comment by smiths** [comment]
@salahhessien, even though we pretend that there is a "domain expert", there really isn't.  When we say "domain expert", we just mean the same person that sticks with a project throughout the term.

Your issues do not have to be clever or deep.  If you don't understand something in the documentation of @JohnErnsthausen, that can be made into an issue.  The resolution of the issue might just be @JohnErnsthausen answering your question in a comment, rather than changes to the documentation, but it will still be helpful to @JohnErnsthausen.  If our documentation cannot be read by graduate students, even those in a different domain, then we need to provide more information.

Since there is no action for @JohnErnsthausen to take for this issue particular, I will close it.
