### ISSUE TITLE
VnV Plan: What happens if the series does not converge?

### ISSUE THREAD

**Issue by liziscool** [JohnErnsthausen/roc#8]
Hi @JohnErnsthausen,

So I am not super confident in my background knowledge but from my understanding not all series converge? Do you need a test case for something like this? I'm not sure what you would expect to happen by my concern is that your program would just run forever. Maybe it is the user's responsibility to make sure the series is actually convergent?

Anyways I am not sure which of your requirements this would fall under, but it seems like a 'boundary case' that you may want to address!

Otherwise, I think your test cases are very appropriate. 

Found here: https://github.com/JohnErnsthausen/roc/blob/master/docs/VnVPlan/VnVPlan.pdf 
section 5.1

**Comment by liziscool** [comment]
Ohh wait I think the length N is specified so it should not run forever, but I still think there might need to be some warning to the user that it does not converge...

**Comment by JohnErnsthausen** [comment]
Hello @liziscool and @smiths 

Your comments about convergence are quite deep. As a result, I have thought about convergence a lot.

On a theoretical level, one could say that my entire project is about assuring the user that in the limit as N goes to infinity the partial sum from 0 to N of the power series centered at x0 and evaluated at some x converges. Actually I SEEK for this guarantee which is the Radius of Convergence RC. See the very first sentence of 

https://en.wikipedia.org/wiki/Radius_of_convergence

SUPPOSE I know RC, then I know for any point x at which I evaluate the power series that is inside the circle of radius RC and centered at x0 that the limit of partial sums will exist. The limit of partial sums does not exist for x outside the circle centered at x0 of radius RC, and points on the circle of convergence must be investigated separately.

I am computing my RC based on a finite number of terms N. Lot's can go wrong without the convergence of the tail Assumption A1, which the user must show is true. For example, EVERY finite sum converges, it is just a polynomial.

The assumption that the power series is real is meaningful to this project because real power series can only have real poles and complex conjugate pairs of poles and no poles (entire). Sometimes more than one pole can be (almost) equidistant from the current point. Add some mathematical razzle-dazzle. Find that each of these cases involve a best least squares fitting of some portion of the given N coefficients to a model problem, an algorithm that will finish within a finite number of steps. So the program will not run forever.

However the identification of the correct model problem perhaps based on some (yet to be defined) error is a convergence problem I do not yet understand. Perhaps you weren't exactly thinking of this issue, but I do thank you for your question as it provoked me to think deeply about it!
